### ISSUE TITLE
Implement architecture code for Zowe Chat - configuration

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#27]
Implement architecture code for Zowe Chat - configuration:

- [ ] Create and read YAML configuration files for Zowe Chat server and 3 chat tools
- [ ] Define configuration interface and write configuration class

**Comment by MarkAckert** [comment]
Similar to my comment on the logging issue - Imperative's configuration could be reviewed for ideas and inspiration. Imperative's configuration structure is not as directly applicable as its logging is for ChatBot, since Imperative expects to run on client machines with multiple levels of config (global, project, user), while ChatBot presumably has a single configuration file to start with. 

https://github.com/zowe/imperative/

packages/config
