### ISSUE TITLE
Implement architecture code for Zowe Chat - logging

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#33]
Implement architecture code for Zowe Chat - logging

- [ ] Write code to provide logging for Zowe Chat

**Comment by MarkAckert** [comment]
I suggest looking at how Imperative handled logging in a common framework - https://github.com/zowe/imperative , under packages/logging. Imperative solves a similar problem as a library providing common functions to downstream extenders (CLI and its plugins). We don't have to use Log4js like Imperative did - I don't have a strong opinion on the specific framework since they appear to have relative parity at a glance - but the structure in Imperative's logging code could be used as inspiration.
