### ISSUE TITLE
Collect feedback from chat survey for chatbot

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-chat#5]
---------------------------
Your feedback matters!

Currently we are working on improving the user experience of Zowe with new features. For better fit into the realities of users’ business scenarios and improve the user experience, we got a survey to understand your current workflow, scenarios, pain points and then see how the new feature could help.
This survey may take 3-4 minutes to complete and it can help us validate our design and assumption in advance. We really appreciate your time and your comments are completely anonymous.
[https://www.surveymonkey.com/r/YCCSXJG](https://www.surveymonkey.com/r/YCCSXJG)
For non-mainframer, who might not directly interact with mainframe but consume mainframe data in your daily work, your feedback is also helpful: [https://www.surveymonkey.com/r/N7TVB7X](https://www.surveymonkey.com/r/N7TVB7X)
Come and help us shape the future of Zowe and Z.

**Comment by Phoebecdy91** [comment]
In total we got 9 responses and 5 of them (one from IBM, one from Broadcom) are willing to join our sponsor user activities, which means that we can invite them to take the usability test.
Will close this issue since we have completed the survey. But will continue to try to connect the sponsor users to see whether they would love to join the usability test.
