### ISSUE TITLE
Research - Supporting a subset of commands

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-chat#77]
Zowe ChatBot's Technical Preview will use a command format which is based on Zowe CLI's command structure. However, we will not support ever optional the CLI exposes to its users.  In coordination with and following #76 ,  how should we express the parameters which we do support? Deny or ignore the parameters we don't? Are unsupported parameters an error condition?

**Comment by Wusong-Fang** [comment]
- Background:

  Zowe Chat can’t support all Zowe CLI commands, including options due to the main usage context is totally different
  Zowe CLI SDK can’t provide all functions required by Zowe Chat such as command parsing and syntax check, get inline help, hide some commands or some options.

- Pros:

  - No learning time for end users

- Cons:

  - Heaviely impacted by Zowe CLI commands including SDK
  - Keep synchronizing changes from Zowe CLI
  - No way to hide some commands and options
  - More additional efforts to support new command required by Zowe Chat
  - More communication and pending time for issues
  - More confusion brough about to end users: why some commands and options are not supported, why the command output is totally different 
  - Some command is a little complex, not friendly for chatting event as internal communication language 
  - Need new option --native to tell Zowe Chat server run command locally and natively

**Comment by Wusong-Fang** [comment]
Per the discussion result of squad meeting, we finally decide to use Zowe Chat its own command. So close the issue. 
Moreover, Zowe CLI commands will be supported to be run natively on Zowe Chat server.
