### ISSUE TITLE
Investigate all possibles ways for Zowe Chat authentication

### ISSUE THREAD

**Issue by Wusong-Fang** [zowe/zowe-chat#9]
- Investigate all possible ways to link chat tool user ID with RACF ID: one configuration app in Zowe Desktop?
- Implement hello world code

**Comment by MacNale** [comment]
Taylor, as a system programmer, wants to enable 'jobs' Zowe bot in the Microsoft Teams, so that he enables the application team to enquire about the jos status performance without leaving the channel.
- Taylor wants to ensure that 'jobs' zowe bot is trustworthy
- Taylor is clear about the bot installation and has necessary permissions to enable bot interactions with its production system
- Taylor has enough auditing to track the bots activity. 
- Taylor has enough control on the bots ability

I am not sure if the persona is right.

**Comment by MarkAckert** [comment]
This chart contains an early initial design, please leave comments either here or in the document. If you cannot access the link, let me know.

https://broadcom.ent.box.com/file/968613615982
